---
- name: Ensure timers directory exists
  file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory

- name: Ensure timers directory exists
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory

- name: Change the apt-daily timer
  template:
    src: apt-daily.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Change the apt-daily-upgrade timer
  template:
    src: apt-daily-upgrade.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart apt-daily.timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted
    enabled: yes

- name: Restart apt-daily-upgrade.timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    enabled: yes
